name: Run R Script with Secret

on:
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          R -e 'install.packages("httr")'
          R -e 'install.packages("jsonlite")'
          R -e 'install.packages("sodium")'
          R -e 'install.packages("httr2")'
          R -e 'install.packages("curl")'
          R -e 'install.packages("data.table")'
          R -e 'install.packages("readxl")'
          R -e 'install.packages("rio")'
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("tidyr")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("purrr")'
          R -e 'install.packages("tibble")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("forcats")'
          R -e 'install.packages("magrittr")'
          R -e 'install.packages("glue")'

      - name: Check R Library Paths
        run: |
          Rscript -e 'print(.libPaths())'

      - name: Validate Installed Packages
        run: |
          Rscript -e 'print(installed.packages())'

      - name: Run R Script with Secret Variables
        env:
          LSPDAUTH_LSPDACCESSTOKEN: ${{ secrets.LSPDAUTH_LSPDACCESSTOKEN }}
          LSPDAUTH_LSPDAPINAME: ${{ secrets.LSPDAUTH_LSPDAPINAME }}
          LSPDAUTH_LSPDCLIENTID: ${{ secrets.LSPDAUTH_LSPDCLIENTID }}
          LSPDAUTH_LSPDCLIENTSECRETKEY: ${{ secrets.LSPDAUTH_LSPDCLIENTSECRETKEY }}
          LSPDAUTH_LSPDREFRESHTOKEN: ${{ secrets.LSPDAUTH_LSPDREFRESHTOKEN }}
        run: |
          Rscript InventoryGithubUpdate.R
