name: Run R Script with Secret

on:
  schedule:
    # Runs at 10:00 PM UTC every day
    - cron: "0 22 * * *"
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr2
            any::curl
            any::data.table
            any::jsonlite
            any::readxl
            any::rio
            any::sodium
            any::httr

      - name: Run R Script with Secret Variables
        env:
          LSPDAUTH_LSPDACCESSTOKEN: ${{ secrets.LSPDAUTH_LSPDACCESSTOKEN }}
          LSPDAUTH_LSPDAPINAME: ${{ secrets.LSPDAUTH_LSPDAPINAME }}
          LSPDAUTH_LSPDCLIENTID: ${{ secrets.LSPDAUTH_LSPDCLIENTID }}
          LSPDAUTH_LSPDCLIENTSECRETKEY: ${{ secrets.LSPDAUTH_LSPDCLIENTSECRETKEY }}
          LSPDAUTH_LSPDREFRESHTOKEN: ${{ secrets.LSPDAUTH_LSPDREFRESHTOKEN }}
        run: |
          Rscript InventoryGithubUpdate.R
