name: Run R Script with Secret

on:
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("httr", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("jsonlite", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("sodium", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("httr2", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("curl", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("data.table", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("readxl", lib = "/usr/local/lib/R/site-library")'
          R -e 'install.packages("rio", lib = "/usr/local/lib/R/site-library")'

      - name: Check R Library Paths
        run: |
          Rscript -e 'print(.libPaths())'

      - name: Validate Installed Packages
        run: |
          Rscript -e 'print(installed.packages())'

      - name: Run R Script with Secret Variables
        env:
          LSPDAUTH_LSPDACCESSTOKEN: ${{ secrets.LSPDAUTH_LSPDACCESSTOKEN }}
          LSPDAUTH_LSPDAPINAME: ${{ secrets.LSPDAUTH_LSPDAPINAME }}
          LSPDAUTH_LSPDCLIENTID: ${{ secrets.LSPDAUTH_LSPDCLIENTID }}
          LSPDAUTH_LSPDCLIENTSECRETKEY: ${{ secrets.LSPDAUTH_LSPDCLIENTSECRETKEY }}
          LSPDAUTH_LSPDREFRESHTOKEN: ${{ secrets.LSPDAUTH_LSPDREFRESHTOKEN }}
        run: |
          Rscript InventoryGithubUpdate.R
