name: Run R Script with Secret

on:
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
              uses: r-lib/actions/setup-r-dependencies@v2
              with:
                packages: |
                  any::httr 
                  any::jsonlite
                  any::sodium
                  any::tidyverse
                  any::httr2
                  any::curl
                  any::data.table
                  any::readxl
                  any::rio
                  
      - name: Run R Script with Secret Variables
        env:
          LSPDAUTH_LSPDACCESSTOKEN: ${{ secrets.LSPDAUTH_LSPDACCESSTOKEN }}
          LSPDAUTH_LSPDAPINAME: ${{ secrets.LSPDAUTH_LSPDAPINAME }}
          LSPDAUTH_LSPDCLIENTID: ${{ secrets.LSPDAUTH_LSPDCLIENTID }}
          LSPDAUTH_LSPDCLIENTSECRETKEY: ${{ secrets.LSPDAUTH_LSPDCLIENTSECRETKEY }}
          LSPDAUTH_LSPDREFRESHTOKEN: ${{ secrets.LSPDAUTH_LSPDREFRESHTOKEN }}
        run: |
          Rscript InventoryGithubUpdate.R
